# NumPy

In [1]:
import numpy as np

In [2]:
python_lista = [1, 2, 3, 4, 5]
numpy_ndarray = np.array([1, 2, 3, 4, 5])

print(f'Mnozenje Python liste {python_lista * 2}')
print(f'Mnozenje NumPy ndArray {numpy_ndarray * 2}')

Mnozenje Python liste [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Mnozenje NumPy ndArray [ 2  4  6  8 10]


In [6]:
# [element * 2 for element in python_lista]
# ili
np.multiply(python_lista, 2)

array([ 2,  4,  6,  8, 10])

In [7]:
python_lista = []
np.multiply(python_lista, 2)

array([], dtype=float64)

In [9]:
podaci = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(podaci)

np_podaci = np.array(podaci)
print(np_podaci)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
np_podaci.size

9

In [11]:
np_podaci.ndim

2

In [12]:
podaci = [[1, 2, 3], [4, 5, 6], [7, 8]]
print(podaci)

np_podaci = np.array(podaci)
print(np_podaci)

[[1, 2, 3], [4, 5, 6], [7, 8]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [13]:
lista = [
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]],
    [[17, 18 ,19, 20], [21, 22, 23, 24], [25, 26, 27, 28], [29, 30, 31, 32]],
    [[33, 34, 35, 36], [37, 38, 39, 40], [41, 42, 43, 44], [45, 46, 47, 48]]
]

np_lista = np.array(lista)
np_lista

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

In [14]:
np_lista.ndim

3

In [15]:
np_lista.size

48

In [16]:
np_lista.shape

(3, 4, 4)

In [17]:
np_podaci.shape

(3, 3)

In [25]:
print('bytes', np_lista.nbytes)
print('item size', np_lista.itemsize)
print('size', np_lista.size)
print('dtype', np_lista.dtype)
print()
print('bytes', np_podaci.nbytes)
print('item size', np_podaci.itemsize)
print('size', np_podaci.size)
print('dtype', np_podaci.dtype)

bytes 384
item size 8
size 48
dtype int64

bytes 72
item size 8
size 9
dtype int64


In [26]:
np_lista = np.array(np_lista, dtype=np.int16)

print('bytes', np_lista.nbytes)
print('item size', np_lista.itemsize)
print('size', np_lista.size)
print('dtype', np_lista.dtype)

bytes 96
item size 2
size 48
dtype int16


In [27]:
np_lista = np.array(np_lista, dtype=np.float64)
np_lista

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]],

       [[17., 18., 19., 20.],
        [21., 22., 23., 24.],
        [25., 26., 27., 28.],
        [29., 30., 31., 32.]],

       [[33., 34., 35., 36.],
        [37., 38., 39., 40.],
        [41., 42., 43., 44.],
        [45., 46., 47., 48.]]])

In [28]:
print('bytes', np_lista.nbytes)
print('item size', np_lista.itemsize)
print('size', np_lista.size)
print('dtype', np_lista.dtype)

bytes 384
item size 8
size 48
dtype float64


In [29]:
np_lista.shape

(3, 4, 4)

In [30]:
np_lista.size

48

In [31]:
np.ndarray.reshape?

Signature: np.ndarray.reshape(self, /, *shape, order='C', copy=None)
Docstring:
a.reshape(shape, /, *, order='C', copy=None)
a.reshape(*shape, order='C', copy=None)

Returns an array containing the same data with a new shape.

Refer to `numpy.reshape` for full documentation.

See Also
--------
numpy.reshape : equivalent function

Notes
-----
Unlike the free function `numpy.reshape`, this method on `ndarray` allows
the elements of the shape parameter to be passed in as separate arguments.
For example, ``a.reshape(4, 2)`` is equivalent to ``a.reshape((4, 2))``.
Type:      method_descriptor

In [41]:
# (3, 4, 4)

# np_lista = np_lista.reshape(6, 8)
# np_lista = np_lista.reshape(12, 4)
np_lista = np_lista.reshape(48)
np_lista

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48.])

In [40]:
np_lista.ndim

1

In [45]:
zeros = np.zeros((3, 4, 4))
zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [49]:
jedinice = np.ones((3, 4, 4), dtype=np.int64)
jedinice

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [50]:
dvojke = jedinice * 2
dvojke

array([[[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]]])

In [51]:
sedmice = np.full((3, 3, 5), 7)
sedmice

array([[[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]],

       [[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]],

       [[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]]])

In [54]:
# range(start, stop, step)
# np.arange(5)
# np.arange(5, 15)
np.arange(5, 15, 3)

array([ 5,  8, 11, 14])

In [55]:
np.linspace(5, 15, 3)

array([ 5., 10., 15.])

In [56]:
np.linspace(5, 15, 5)

array([ 5. ,  7.5, 10. , 12.5, 15. ])

In [60]:
# od 1 do 48 uklj
# 3, 4, 4
np.linspace(1, 48, 48, dtype=np.int64).reshape(3, 4, 4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

In [59]:
np.arange(1, 49).reshape(3, 4, 4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

In [62]:
np_polje = np.arange(1, 37).reshape(6, 6)
np_polje

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [66]:
np_polje[1]
np_polje[1][0]

np.int64(7)

In [67]:
np_polje[ : 3]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [68]:
# slice notacija prvi set indeksa koristi za redove, a zadnji za stupce
np_polje[ : 3, 3 : 5]

array([[ 4,  5],
       [10, 11],
       [16, 17]])

In [70]:
np_polje = np.arange(1, 28).reshape(3, 3, 3)
np_polje

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [76]:
np_polje[:3, 1:3, 1:3]

array([[[ 5,  6],
        [ 8,  9]],

       [[14, 15],
        [17, 18]],

       [[23, 24],
        [26, 27]]])

In [75]:
np_polje[1:3, 2, 2]

array([18, 27])

Kreirajte funkciju, naziva *funkcija*, koja prima dva argumenta i vraca njihov umnozak s brojem 5

In [77]:
def funkcija(x, y):
    return x * y * 5


np.fromfunction(funkcija, (5, 8), dtype=np.int64)

array([[  0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   5,  10,  15,  20,  25,  30,  35],
       [  0,  10,  20,  30,  40,  50,  60,  70],
       [  0,  15,  30,  45,  60,  75,  90, 105],
       [  0,  20,  40,  60,  80, 100, 120, 140]])

Prepravite gornji primjer tako da ispisuje tablicu mnozenja do 15

In [83]:
def tablica_mnozenja(x, y):
    return x * y


nd_tablica_mnozenja = np.fromfunction(tablica_mnozenja, (16, 16), dtype=np.int64)
nd_tablica_mnozenja = nd_tablica_mnozenja[ 1: , 1:]
nd_tablica_mnozenja

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,  39,
         42,  45],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,  52,
         56,  60],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,  78,
         84,  90],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,  91,
         98, 105],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96, 104,
        112, 120],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108, 117,
        126, 135],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132, 143,
       

In [84]:
nd_tablica_mnozenja_do_10 = nd_tablica_mnozenja[ :10 , :10 ]
nd_tablica_mnozenja_do_10

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [85]:
nd_tablica_mnozenja_do_10[4:6, 4:6] = 99999
nd_tablica_mnozenja_do_10

array([[    1,     2,     3,     4,     5,     6,     7,     8,     9,
           10],
       [    2,     4,     6,     8,    10,    12,    14,    16,    18,
           20],
       [    3,     6,     9,    12,    15,    18,    21,    24,    27,
           30],
       [    4,     8,    12,    16,    20,    24,    28,    32,    36,
           40],
       [    5,    10,    15,    20, 99999, 99999,    35,    40,    45,
           50],
       [    6,    12,    18,    24, 99999, 99999,    42,    48,    54,
           60],
       [    7,    14,    21,    28,    35,    42,    49,    56,    63,
           70],
       [    8,    16,    24,    32,    40,    48,    56,    64,    72,
           80],
       [    9,    18,    27,    36,    45,    54,    63,    72,    81,
           90],
       [   10,    20,    30,    40,    50,    60,    70,    80,    90,
          100]])

In [86]:
nd_tablica_mnozenja

array([[    1,     2,     3,     4,     5,     6,     7,     8,     9,
           10,    11,    12,    13,    14,    15],
       [    2,     4,     6,     8,    10,    12,    14,    16,    18,
           20,    22,    24,    26,    28,    30],
       [    3,     6,     9,    12,    15,    18,    21,    24,    27,
           30,    33,    36,    39,    42,    45],
       [    4,     8,    12,    16,    20,    24,    28,    32,    36,
           40,    44,    48,    52,    56,    60],
       [    5,    10,    15,    20, 99999, 99999,    35,    40,    45,
           50,    55,    60,    65,    70,    75],
       [    6,    12,    18,    24, 99999, 99999,    42,    48,    54,
           60,    66,    72,    78,    84,    90],
       [    7,    14,    21,    28,    35,    42,    49,    56,    63,
           70,    77,    84,    91,    98,   105],
       [    8,    16,    24,    32,    40,    48,    56,    64,    72,
           80,    88,    96,   104,   112,   120],
       [    9,    18,   

In [87]:
def tablica_mnozenja(x, y):
    return x * y


nd_tablica_mnozenja = np.fromfunction(tablica_mnozenja, (16, 16), dtype=np.int64)
nd_tablica_mnozenja = nd_tablica_mnozenja[ 1: , 1:]
nd_tablica_mnozenja

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,  39,
         42,  45],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,  52,
         56,  60],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,  78,
         84,  90],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,  91,
         98, 105],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96, 104,
        112, 120],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108, 117,
        126, 135],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132, 143,
       

In [88]:
nd_tablica_mnozenja_do_10 = nd_tablica_mnozenja[ :10 , :10 ].copy()
nd_tablica_mnozenja_do_10

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [89]:
nd_tablica_mnozenja_do_10[4:6, 4:6] = 99999
nd_tablica_mnozenja_do_10

array([[    1,     2,     3,     4,     5,     6,     7,     8,     9,
           10],
       [    2,     4,     6,     8,    10,    12,    14,    16,    18,
           20],
       [    3,     6,     9,    12,    15,    18,    21,    24,    27,
           30],
       [    4,     8,    12,    16,    20,    24,    28,    32,    36,
           40],
       [    5,    10,    15,    20, 99999, 99999,    35,    40,    45,
           50],
       [    6,    12,    18,    24, 99999, 99999,    42,    48,    54,
           60],
       [    7,    14,    21,    28,    35,    42,    49,    56,    63,
           70],
       [    8,    16,    24,    32,    40,    48,    56,    64,    72,
           80],
       [    9,    18,    27,    36,    45,    54,    63,    72,    81,
           90],
       [   10,    20,    30,    40,    50,    60,    70,    80,    90,
          100]])

In [90]:
nd_tablica_mnozenja

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,  39,
         42,  45],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,  52,
         56,  60],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,  78,
         84,  90],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,  91,
         98, 105],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96, 104,
        112, 120],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108, 117,
        126, 135],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132, 143,
       

In [93]:
niz1 = np.array([[1, 2, 3], [4, 5, 6]])
print(niz1)
print()
niz2 = np.array([[7, 8, 9], [10, 11, 12]])
print(niz2)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]


In [94]:
np.concatenate([niz1, niz2], axis=0) # Os 0 predstavlja y os, odnosno vertikalni smjer, a os 1 predstavlja x os ili horizontalni smjer

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [95]:
np.concatenate([niz1, niz2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [97]:
np.vstack((niz1, niz2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [98]:
np.hstack((niz1, niz2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [99]:
niz = np.arange(1, 17).reshape(4, 4)
niz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [100]:
np.hsplit(niz, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [101]:
np.vsplit(niz, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]